//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_dlya_chatbota_ver3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Настройки опр.
    /// </summary>
    // *** Start programmer edit section *** (НастройкиОпр CustomAttributes)

    // *** End programmer edit section *** (НастройкиОпр CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НастройкиОпрE", new string[] {
            "Опрос as \'Опрос\'",
            "Опрос.Наименование as \'Опрос\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Фамилия as \'Ответственный\'"}, Hidden=new string[] {
            "Опрос.Наименование",
            "Сотрудники.Фамилия"})]
    [AssociatedDetailViewAttribute("НастройкиОпрE", "Содержание", "СодержаниеE", true, "", "Содержание", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("НастройкиОпрE", "Опрос", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("НастройкиОпрE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("НастройкиОпрL", new string[] {
            "Опрос.Наименование as \'Опрос\'",
            "Сотрудники.Фамилия as \'Ответственный\'"})]
    public class НастройкиОпр : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Modul_dlya_chatbota_ver3.Опрос fОпрос;
        
        private IIS.Modul_dlya_chatbota_ver3.Сотрудники fСотрудники;
        
        private IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание fСодержание;
        
        // *** Start programmer edit section *** (НастройкиОпр CustomMembers)

        // *** End programmer edit section *** (НастройкиОпр CustomMembers)

        
        /// <summary>
        /// Настройки опр.
        /// </summary>
        // *** Start programmer edit section *** (НастройкиОпр.Опрос CustomAttributes)

        // *** End programmer edit section *** (НастройкиОпр.Опрос CustomAttributes)
        [PropertyStorage(new string[] {
                "Опрос"})]
        [NotNull()]
        public virtual IIS.Modul_dlya_chatbota_ver3.Опрос Опрос
        {
            get
            {
                // *** Start programmer edit section *** (НастройкиОпр.Опрос Get start)

                // *** End programmer edit section *** (НастройкиОпр.Опрос Get start)
                IIS.Modul_dlya_chatbota_ver3.Опрос result = this.fОпрос;
                // *** Start programmer edit section *** (НастройкиОпр.Опрос Get end)

                // *** End programmer edit section *** (НастройкиОпр.Опрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НастройкиОпр.Опрос Set start)

                // *** End programmer edit section *** (НастройкиОпр.Опрос Set start)
                this.fОпрос = value;
                // *** Start programmer edit section *** (НастройкиОпр.Опрос Set end)

                // *** End programmer edit section *** (НастройкиОпр.Опрос Set end)
            }
        }
        
        /// <summary>
        /// Настройки опр.
        /// </summary>
        // *** Start programmer edit section *** (НастройкиОпр.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (НастройкиОпр.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Modul_dlya_chatbota_ver3.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (НастройкиОпр.Сотрудники Get start)

                // *** End programmer edit section *** (НастройкиОпр.Сотрудники Get start)
                IIS.Modul_dlya_chatbota_ver3.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (НастройкиОпр.Сотрудники Get end)

                // *** End programmer edit section *** (НастройкиОпр.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НастройкиОпр.Сотрудники Set start)

                // *** End programmer edit section *** (НастройкиОпр.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (НастройкиОпр.Сотрудники Set end)

                // *** End programmer edit section *** (НастройкиОпр.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Настройки опр.
        /// </summary>
        // *** Start programmer edit section *** (НастройкиОпр.Содержание CustomAttributes)

        // *** End programmer edit section *** (НастройкиОпр.Содержание CustomAttributes)
        public virtual IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание Содержание
        {
            get
            {
                // *** Start programmer edit section *** (НастройкиОпр.Содержание Get start)

                // *** End programmer edit section *** (НастройкиОпр.Содержание Get start)
                if ((this.fСодержание == null))
                {
                    this.fСодержание = new IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание(this);
                }
                IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание result = this.fСодержание;
                // *** Start programmer edit section *** (НастройкиОпр.Содержание Get end)

                // *** End programmer edit section *** (НастройкиОпр.Содержание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НастройкиОпр.Содержание Set start)

                // *** End programmer edit section *** (НастройкиОпр.Содержание Set start)
                this.fСодержание = value;
                // *** Start programmer edit section *** (НастройкиОпр.Содержание Set end)

                // *** End programmer edit section *** (НастройкиОпр.Содержание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НастройкиОпрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НастройкиОпрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НастройкиОпрE", typeof(IIS.Modul_dlya_chatbota_ver3.НастройкиОпр));
                }
            }
            
            /// <summary>
            /// "НастройкиОпрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НастройкиОпрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НастройкиОпрL", typeof(IIS.Modul_dlya_chatbota_ver3.НастройкиОпр));
                }
            }
        }
    }
}
