//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_dlya_chatbota_ver3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опрос.
    /// </summary>
    // *** Start programmer edit section *** (Опрос CustomAttributes)

    // *** End programmer edit section *** (Опрос CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОпросE", new string[] {
            "КодОпроса as \'Код опроса\'",
            "Наименование as \'Наименование\'"})]
    [View("ОпросL", new string[] {
            "КодОпроса as \'Код опроса\'",
            "Наименование as \'Наименование\'"})]
    public class Опрос : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодОпроса;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Опрос CustomMembers)

        // *** End programmer edit section *** (Опрос CustomMembers)

        
        /// <summary>
        /// КодОпроса.
        /// </summary>
        // *** Start programmer edit section *** (Опрос.КодОпроса CustomAttributes)

        // *** End programmer edit section *** (Опрос.КодОпроса CustomAttributes)
        public virtual int КодОпроса
        {
            get
            {
                // *** Start programmer edit section *** (Опрос.КодОпроса Get start)

                // *** End programmer edit section *** (Опрос.КодОпроса Get start)
                int result = this.fКодОпроса;
                // *** Start programmer edit section *** (Опрос.КодОпроса Get end)

                // *** End programmer edit section *** (Опрос.КодОпроса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опрос.КодОпроса Set start)

                // *** End programmer edit section *** (Опрос.КодОпроса Set start)
                this.fКодОпроса = value;
                // *** Start programmer edit section *** (Опрос.КодОпроса Set end)

                // *** End programmer edit section *** (Опрос.КодОпроса Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Опрос.Наименование CustomAttributes)

        // *** End programmer edit section *** (Опрос.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Опрос.Наименование Get start)

                // *** End programmer edit section *** (Опрос.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Опрос.Наименование Get end)

                // *** End programmer edit section *** (Опрос.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Опрос.Наименование Set start)

                // *** End programmer edit section *** (Опрос.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Опрос.Наименование Set end)

                // *** End programmer edit section *** (Опрос.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОпросE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпросE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпросE", typeof(IIS.Modul_dlya_chatbota_ver3.Опрос));
                }
            }
            
            /// <summary>
            /// "ОпросL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОпросL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОпросL", typeof(IIS.Modul_dlya_chatbota_ver3.Опрос));
                }
            }
        }
    }
}
