//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_dlya_chatbota_ver3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Содержание.
    /// </summary>
    // *** Start programmer edit section *** (Содержание CustomAttributes)

    // *** End programmer edit section *** (Содержание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СодержаниеE", new string[] {
            "Вопрос as \'Вопрос\'",
            "Вариант_1 as \'Вариант_1\'",
            "Вариант_2 as \'Вариант_2\'",
            "Вариант_3 as \'Вариант_3\'"})]
    public class Содержание : ICSSoft.STORMNET.DataObject
    {
        
        private string fВопрос;
        
        private string fВариант_1;
        
        private string fВариант_2;
        
        private string fВариант_3;
        
        private IIS.Modul_dlya_chatbota_ver3.НастройкиОпр fНастройкиОпр;
        
        // *** Start programmer edit section *** (Содержание CustomMembers)

        // *** End programmer edit section *** (Содержание CustomMembers)

        
        /// <summary>
        /// Вариант_1.
        /// </summary>
        // *** Start programmer edit section *** (Содержание.Вариант_1 CustomAttributes)

        // *** End programmer edit section *** (Содержание.Вариант_1 CustomAttributes)
        [StrLen(255)]
        public virtual string Вариант_1
        {
            get
            {
                // *** Start programmer edit section *** (Содержание.Вариант_1 Get start)

                // *** End programmer edit section *** (Содержание.Вариант_1 Get start)
                string result = this.fВариант_1;
                // *** Start programmer edit section *** (Содержание.Вариант_1 Get end)

                // *** End programmer edit section *** (Содержание.Вариант_1 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Содержание.Вариант_1 Set start)

                // *** End programmer edit section *** (Содержание.Вариант_1 Set start)
                this.fВариант_1 = value;
                // *** Start programmer edit section *** (Содержание.Вариант_1 Set end)

                // *** End programmer edit section *** (Содержание.Вариант_1 Set end)
            }
        }
        
        /// <summary>
        /// Вариант_2.
        /// </summary>
        // *** Start programmer edit section *** (Содержание.Вариант_2 CustomAttributes)

        // *** End programmer edit section *** (Содержание.Вариант_2 CustomAttributes)
        [StrLen(255)]
        public virtual string Вариант_2
        {
            get
            {
                // *** Start programmer edit section *** (Содержание.Вариант_2 Get start)

                // *** End programmer edit section *** (Содержание.Вариант_2 Get start)
                string result = this.fВариант_2;
                // *** Start programmer edit section *** (Содержание.Вариант_2 Get end)

                // *** End programmer edit section *** (Содержание.Вариант_2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Содержание.Вариант_2 Set start)

                // *** End programmer edit section *** (Содержание.Вариант_2 Set start)
                this.fВариант_2 = value;
                // *** Start programmer edit section *** (Содержание.Вариант_2 Set end)

                // *** End programmer edit section *** (Содержание.Вариант_2 Set end)
            }
        }
        
        /// <summary>
        /// Вариант_3.
        /// </summary>
        // *** Start programmer edit section *** (Содержание.Вариант_3 CustomAttributes)

        // *** End programmer edit section *** (Содержание.Вариант_3 CustomAttributes)
        [StrLen(255)]
        public virtual string Вариант_3
        {
            get
            {
                // *** Start programmer edit section *** (Содержание.Вариант_3 Get start)

                // *** End programmer edit section *** (Содержание.Вариант_3 Get start)
                string result = this.fВариант_3;
                // *** Start programmer edit section *** (Содержание.Вариант_3 Get end)

                // *** End programmer edit section *** (Содержание.Вариант_3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Содержание.Вариант_3 Set start)

                // *** End programmer edit section *** (Содержание.Вариант_3 Set start)
                this.fВариант_3 = value;
                // *** Start programmer edit section *** (Содержание.Вариант_3 Set end)

                // *** End programmer edit section *** (Содержание.Вариант_3 Set end)
            }
        }
        
        /// <summary>
        /// Вопрос.
        /// </summary>
        // *** Start programmer edit section *** (Содержание.Вопрос CustomAttributes)

        // *** End programmer edit section *** (Содержание.Вопрос CustomAttributes)
        [StrLen(255)]
        public virtual string Вопрос
        {
            get
            {
                // *** Start programmer edit section *** (Содержание.Вопрос Get start)

                // *** End programmer edit section *** (Содержание.Вопрос Get start)
                string result = this.fВопрос;
                // *** Start programmer edit section *** (Содержание.Вопрос Get end)

                // *** End programmer edit section *** (Содержание.Вопрос Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Содержание.Вопрос Set start)

                // *** End programmer edit section *** (Содержание.Вопрос Set start)
                this.fВопрос = value;
                // *** Start programmer edit section *** (Содержание.Вопрос Set end)

                // *** End programmer edit section *** (Содержание.Вопрос Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Modul_dlya_chatbota_ver3.НастройкиОпр.
        /// </summary>
        // *** Start programmer edit section *** (Содержание.НастройкиОпр CustomAttributes)

        // *** End programmer edit section *** (Содержание.НастройкиОпр CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "НастройкиОпр"})]
        public virtual IIS.Modul_dlya_chatbota_ver3.НастройкиОпр НастройкиОпр
        {
            get
            {
                // *** Start programmer edit section *** (Содержание.НастройкиОпр Get start)

                // *** End programmer edit section *** (Содержание.НастройкиОпр Get start)
                IIS.Modul_dlya_chatbota_ver3.НастройкиОпр result = this.fНастройкиОпр;
                // *** Start programmer edit section *** (Содержание.НастройкиОпр Get end)

                // *** End programmer edit section *** (Содержание.НастройкиОпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Содержание.НастройкиОпр Set start)

                // *** End programmer edit section *** (Содержание.НастройкиОпр Set start)
                this.fНастройкиОпр = value;
                // *** Start programmer edit section *** (Содержание.НастройкиОпр Set end)

                // *** End programmer edit section *** (Содержание.НастройкиОпр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СодержаниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СодержаниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СодержаниеE", typeof(IIS.Modul_dlya_chatbota_ver3.Содержание));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Содержание.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСодержание CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСодержание CustomAttributes)
    public class DetailArrayOfСодержание : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание members)

        // *** End programmer edit section *** (IIS.Modul_dlya_chatbota_ver3.DetailArrayOfСодержание members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Содержание by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Содержание.
        /// </summary>
        public DetailArrayOfСодержание(IIS.Modul_dlya_chatbota_ver3.НастройкиОпр fНастройкиОпр) : 
                base(typeof(Содержание), ((ICSSoft.STORMNET.DataObject)(fНастройкиОпр)))
        {
        }
        
        public IIS.Modul_dlya_chatbota_ver3.Содержание this[int index]
        {
            get
            {
                return ((IIS.Modul_dlya_chatbota_ver3.Содержание)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Modul_dlya_chatbota_ver3.Содержание dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
