import IISModul_dlya_chatbota_ver3НастройкиОпрEController from '../i-i-s-modul-dlya-chatbota-ver3-настройки-опр-e';

var IISModul_dlya_chatbota_ver3НастройкиОпрENewController = IISModul_dlya_chatbota_ver3НастройкиОпрEController;
export default IISModul_dlya_chatbota_ver3НастройкиОпрENewController;
